server:
  port: 8081
  servlet:
    context-path: /log
spring:
  application:
    name: log
    profiles:
      active: local     # 本地环境
    #    active: dev       # 环境
    #    active: test      # 开发测试环境
    #    active: pre       # 预发环境
    #    active: online    # 生产环境
    # Logback
    log:
      file:
        path: ${home}/log/${spring.application.name}/${spring.profiles.active} # 日志文件路径
        maxKeep: 5  # 最大保留的文件个数
  # health monitor
  info:
    app:
      name: "@project.name@"
      description: "@project.description@"
      version: "@project.version@"
      spring-boot-version: "@spring.boot.version@"

  logging:
    config: classpath:logback-spring.xml
    #level: INFO

  home: \alidata\youngch\upload\ai\static
